# Run tests on gitlab.pasteur.fr after new push
image: docker:latest

services:
    - docker:dind
    - mongo

before_script:
    - docker login -u gitlab-ci-token -p $BIOMAJ_MANAGER_DOCKER registry-gitlab.pasteur.fr

build:
    stage: test
    script:
        - docker run -v $CI_PROJECT_DIR:/builds -t registry-gitlab.pasteur.fr/tuco/biomaj-manager:biomaj-manager /bin/sh /builds/tests/gitlab-tests.sh
