# Run tests on gitlab.pasteur.fr after new push
image: registry-gitlab.pasteur.fr/tuco/biomaj-manager:biomaj-manager

services:
    - mongo

build:
    stage: test
    script:
        - BIOMAJ_MANAGER_DOCKER_CONF=$CI_PROJECT_DIR/tests/global-docker.properties nosetests -q -x
