# Run tests on gitlab.pasteur.fr after new push
image: registry-gitlab.pasteur.fr/tuco/biomaj-manager:biomaj-manager

services:
    - mongo

variables:
    MONGODB_URI: "mongodb://mongo:27017"
    MONGODB_DBNAME: "bm_db_test"

build:
    stage: test
    script:
        - nosetests -q -x
