# Run tests on gitlab.pasteur.fr after new push
image: docker:latest

services:
    - docker:dind

build:
    stage: build
    script:
        - docker build -t biomaj-manager $CI_PROJECT_DIR
        - docker run -v $CI_PROJECT_DIR:/builds biomaj-manager sh /builds/tests/gitlab-tests.sh
