# Run tests on gitlab.pasteur.fr after new push
image: docker:latest

services:
    - docker:dind
    - mongo
# https://gitlab.com/gitlab-org/gitlab-ce/issues/13262
variables:
  MONGO_DATABASE: bm_db_test
  Host: mongo
  Database: bm_db_test

build:
  stage: build
  script:
  - docker build -t biomaj-manager $CI_PROJECT_DIR/tests/
  - docker run biomaj-manager $CI_PROJECT_DIR/tests/gitlab-tests.sh
