# Run tests on gitlab.pasteur.fr after new push
image: registry-gitlab.pasteur.fr/biomaj/biomaj-manager:latest

services:
    - mongo

variables:
    MONGODB_URI: "mongodb://mongo:27017"
    MONGODB_DBNAME: "bm_db_test"

build:
    stage: test
    script:
        - pip install biomaj>=3.1.0 biomaj-core>=3.0.8
        - nosetests -q -x
