language: python
python:
  - "2.7"
  - "3.4"
services:
  - mongodb
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies

install:
  - "pip install -r requirements.txt"
  - "python setup.py -q install"
# command to run tests
script: nosetests --with-coverage
#after_success:
#  - coveralls

